<?php require_once 'public/menuCadastro.phtml';?>

<script type="text/javascript">
<!--

//-->
$(function() {
	$('#opcaoCadastro').addClass('active');
	$('#opcaoMapaExtracao').addClass('active');
	
});

</script>

<?
$title = 'Incluir novo mapa de extração';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?
$form = $this->form;
$form->setAttribute('action', $this->url('mapaextracao', array('action' => 'add')));
$form->prepare();
?>
<?=$this->form()->openTag($form)?>
<?=$this->formCollection($this->form)?>
<?=$this->form()->closeTag()?>