
<?php require_once 'public/menuCadastro.phtml';?>

<script type="text/javascript">
<!--

//-->
$(function() {
	$('#opcaoCadastro').addClass('active');
	$('#opcaoOperador').addClass('active');
	
});

</script>

<?
$title = 'Operadores';
$this->headtitle($title);
?>
<h1><?=$this->escapehtml($title) ?></h1>
<p>
	<a href="<?=$this->url('operador', array('action' => 'add'))?>">
	<button type="button" class="btn btn-primary">Novo Operador</button></a>
</p>

<?=$this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
<?=$this->flashMessenger()->render('error', array('alert', 'alert-danger'));?>

<?
$form = $this->formPesquisa;
$form->setAttribute('action', $this->urlPesquisa);
$form->prepare();
?>
<?=$this->form()->openTag($form)?>
<?=$this->formCollection($form)?>
<?=$this->form()->closeTag()?>

    <br />
<table class="full_table_list">
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Senha</th>
    <th>Ponto</th>
    <th>Ativo</th>
    <th>Ação</th>
  </tr>
    <?=$this->partialLoop('cadastro/operador/operadores.phtml', $this->paginator)?>
</table>
<?=$this->paginationControl($this->paginator, 'Sliding', 'pagination', array('route' => 'operador')); ?>
