
<?php require_once 'public/menuCadastro.phtml';?>

<script type="text/javascript">
<!--

//-->
$(function() {
	$('#opcaoCadastro').addClass('active');
	$('#opcaoPonto').addClass('active');
	
});

</script>
<?
$title = "Remover ponto '".$this->model->codigo.'-'.$this->model->nome."'?";
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?
$form = $this->form; 
$form->setAttribute('action', $this->urlAction);
$form->prepare();
?>
<?=$this->form()->openTag($form)?>
<?=$this->formCollection($this->form)?>
<?=$this->form()->closeTag()?>