<div class="container" style="margin-top: 10px;">
    <div class="row">
        <div class="span12 navbar">
            <div class="navbar-inner">
                <ul class="nav">
                    <li id="opcaoTrocarSenha"><a href="<?= $this->basePath()?>/funcoes/trocarsenha">Trocar Senha</a></li>
                </ul>
                <ul class="nav pull-right">
                  <li><a href="<?=$this->basePath()?>/application/index/logout">[Sair]</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
