<div class="container" style="margin-top: 10px;">
    <div class="row">
        <div class="span12 navbar">
            <div class="navbar-inner">
                <ul class="nav">
                  <li id="opcaoNovoJogo"><a href="<?= $this->basePath()?>/jogar/novojogo">Novo Jogo</a></li>
                  <li id="opcaoPreDatarJogo"><a href="<?= $this->basePath()?>/jogar/predatarjogo">Pré-Datar Jogo</a></li>
                  <li id="opcaoRepetirJogo"><a href="<?= $this->basePath()?>/jogar/repetirjogo">Repetir Jogo</a></li>
                </ul>
                <ul class="nav pull-right">
                  <li><a href="<?=$this->basePath()?>/application/index/logout">[Sair]</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
