<div class="container" style="margin-top: 10px;">
    <div class="row">
        <div class="span12 navbar">
            <div class="navbar-inner">
                <ul class="nav">
                    <li id="opcaoParcial"><a href="<?= $this->basePath()?>/relatorio/parcialdohorario">Parcial do Horário</a></li>
                    <li id="opcaoResultado"><a href="<?= $this->basePath()?>/relatorio/resultado">Resultado</a></li>
                    <li id="opcaoPulePremiada"><a href="<?= $this->basePath()?>/relatorio/pulepremiada">Pule Premiada</a></li>
                    <li id="opcaoVendaPorDia"><a href="<?= $this->basePath()?>/relatorio/vendapordia">Venda por Dia</a></li>
                    <li id="opcaoGuia"><a href="<?= $this->basePath()?>/relatorio/guiamovimento">Guia Movimento</a></li>
                    <li id="opcaoVendaPorExtracao"><a href="<?= $this->basePath()?>/relatorio/vendaporextracao">Venda por Extração</a></li>
                </ul>
                <ul class="nav pull-right">
                  <li><a href="<?=$this->basePath()?>/application/index/logout">[Sair]</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
