<tr>
<td><?=str_pad($this->model->codigo,4, 0, STR_PAD_LEFT)?></td>
    <td><?=$this->escapeHtml($this->model->nome)?></td>
    <td><?=$this->escapeHtml($this->model->sigla)?></td>
    <td><div align="center"><?=$this->model->ativo == 1? 'Sim' : 'Não' ?></div></td>
    <td><div align="center"><?=$this->model->descarga == 1? 'Sim' : 'Não' ?></div></td>
    <td><?=number_format($this->model->premio_valor_mult, 2, ',', '.')?></td>
    <td><?=number_format($this->model->aposta_valor_mult, 2, ',', '.')?></td>
    <td>
        <div align="center">
            <a href="<?=$this->placeholder('url')->edit . '/'. $this->model->id?>"><input type="submit" value="Editar"/></a>
            <a href="<?=$this->placeholder('url')->delete . '/'. $this->model->id?>"><input type="submit" value="Remover"/></a>
        </div>
    </td>
</tr>