<?php
require_once 'vendor/MPDF53/mpdf.php';

$valorTotalApostas = 0;
$qtdApostas = $this->qtd_apostas;
$numPule = $this->numPule;
$extracao = $this->extracao_0_hidden;
$operador = $this->operador;
$terminal = $this->terminal;
$data = $this->data;
$tempoReclamacoes = $this->tempoReclamacoes;
$empresa = $this->empresa;

$apostas = '';

for($i=0; $i<$qtdApostas; $i++){
    $qtd_jogos = $this->{ 'qtd_jogos_'.$i.'_hidden' };
    $tipojogo  = $this->{ 'tipojogo_'.$i.'_hidden' };
    $premioini = $this->{ 'premioini_'.$i.'_hidden' };
    $valorjogo = $this->{ 'valorjogo_'.$i.'_hidden' };
    $valortotal = $this->{ 'valortotal_'.$i.'_hidden' };
    $valorTotalApostas += $valortotal;
    $apostas .= $tipojogo . '<br/>';
    for($j=0; $j<$qtd_jogos; $j++){
        $jogo = $this->{ 'jogo_'.$i.'_'.$j };
        $apostas .= $jogo . ' ';
    }
    $apostas .= '<br/>' . $premioini . ' a ' . $valorjogo .  ' = ' . number_format($valortotal, 2, ',', '.') . ' <br/>';
}
$apostas .= '<h4> ............................................................. </h4>';


$html = '

<head>
	<link rel="stylesheet" href="/pjb/public/css/style.css">
</head>
<div class="boletim" >

<h1>'.$empresa.'</h1>
<h4>Pule: '.$numPule.'</h4>
<h4>Extração: '.$extracao.'</h4>
<h4>Data: '.formata($data, "d/m/Y H:i").'</h4>
<h4>Oper:'.$operador.'  Term:'. $terminal .'</h4>
<h4> --------------- APOSTAS --------------- </h4>
<h4> '. $apostas .'  </h4>
<h4> TOTAL: R$ '. number_format($valorTotalApostas, 2, ',', '.'). '  </h4>
<h4> ............................................................. </h4>
<h4> Reclamações: '.$tempoReclamacoes .' dias</h4>
<h4> ............................................................. </h4>
<h4>'. $terminal .' '. $numPule.'</h4>
<h4> =========================== </h4>

<br />
<table>
        <tr>Pule</tr>
        <tr>Extração</tr>
        <tr>Dia: </tr>
        <tr>Oper: TESTE   Term: </tr>
        <tr>------ APOSTAS ------</tr>
        <tr>------ APOSTAS ------</tr>
        <tr>TOTAL: R$ </tr>
</table>';



        //==============================================================


        $mpdf=new mPDF('c');
        $mpdf->WriteHTML($html);
        $mpdf->Output();
        exit;

        //==============================================================

