<?php
require_once 'vendor/MPDF53/mpdf.php';

$valorTotalApostas = $this->valorTotalApostas;
$qtdApostas = $this->qtd_apostas;
$numPule = $this->numPule;
$extracao = $this->extracao_0_hidden;
$operador = $this->operador;
$terminal = $this->terminal;
$data = $this->data;
$tempoReclamacoes = $this->tempoReclamacoes;
$empresa = $this->empresa;
$jogos = $this->jogos;
$apostas = $this->apostas;
$maxLinha = $this->maxLinha;
$strAposta = str_pad(' APOSTAS ', $maxLinha, '-', STR_PAD_BOTH);
$linhaPreenchida = str_pad('', $maxLinha, '.', STR_PAD_BOTH);

$apostas = '';

/*for($i=0; $i<$qtdApostas; $i++){
    $qtd_jogos = $this->{ 'qtd_jogos_'.$i.'_hidden' };
    $tipojogo  = $this->{ 'tipojogo_'.$i.'_hidden' };
    $premioini = $this->{ 'premioini_'.$i.'_hidden' };
    $valorjogo = $this->{ 'valorjogo_'.$i.'_hidden' };
    $valortotal = $this->{ 'valortotal_'.$i.'_hidden' };
    $valorTotalApostas += $valortotal;
    $apostas .= $tipojogo . '<br/>';
    $apostas .= '<br/>' . $premioini . ' a ' . $valorjogo .  ' = ' . number_format($valortotal, 2, ',', '.') . ' <br/>';
    $apostas .= '<br/>LINHA ' . $this->{ 'linha_'.$i } . ' <br/>';
}*/


$html = '

<head>
	<link rel="stylesheet" href="/terminal-web/public/css/style.css">
	<style>
	body {
        font-family: "Courier New", "Monaco", "monospace";
    }
    </style>
</head>
<div class="boletim" >

<h1>'.$empresa.'</h1>
<h4>Pule: '.$numPule.'</h4>
<h4>Extração: '.$extracao.'</h4>
<h4>Data: '.formata($data, "d/m/Y H:i").'</h4>
<h4>Oper:'.$operador.'  Term:'. $terminal .'</h4>
<h4>' . $strAposta .'</h4>
<h4> '. $jogos .'  </h4>
<h4> TOTAL: R$ '. number_format($valorTotalApostas, 2, ',', '.'). '  </h4>
<h4> ' .$linhaPreenchida. ' </h4>
<h4> Reclamações: '.$tempoReclamacoes .' dias</h4>
<h4> ' .$linhaPreenchida. ' </h4>
<h4>'. $terminal .' '. $numPule.'</h4>
<h4> ' .$linhaPreenchida. ' </h4>

<br />';

        //==============================================================


        $mpdf=new mPDF('c');
        $mpdf->WriteHTML($html);
        $mpdf->Output();
        exit;

        //==============================================================

