
<?php require_once 'public/menuJogar.phtml';?>

<script type="text/javascript">
    $(function() {
        $('#opcaoJogar').addClass('active');
        $('#opcaoNovoJogo').addClass('active');

    });

</script>
<script src="<?=$this->basepath('public/js/funcoesTabela.js') ?>"></script>
<script src="<?=$this->basepath('public/js/funcoesNovoJogo.js') ?>"></script>
<script src="<?=$this->basepath('public/js/jquery.min.js') ?>"></script>

<?

?>
Jogo Jogado!


</p>