<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<?php echo $this->headTitle() ?>
<meta charset="utf-8">
	

	<script src="/js/jquery-1.10.2.js"></script>
	<link rel="stylesheet" href="/w2ui/w2ui-1.3.2.css" />
	<script src="/w2ui/w2ui-1.3.2.js"></script>
	
	<script type="text/javascript" src="/js/menuPrincipal.js"></script>
	
</head>
<body>
	<div id="barraPrincipal"></div>
	<div id="conteudo" class="container">
		<header>
			<p>Controle dos Bichos Frenéticos</p>
		</header>
		<?php echo $this->content; ?>
		<hr>
		<footer>
			<p>
				&copy; 2013 by Oa.
				<?php echo $this->translate('All rights reserved.') ?>
			</p>
		</footer>
	</div>
	<!-- /container -->
</body>
</html>
