<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<?php echo $this->headTitle() ?>
<meta charset="utf-8">
	


	<script src="<?=$this->basepath('public/js/jquery-1.10.2.js') ?>"></script>
	<link rel="stylesheet" href="<?=$this->basepath('public/w2ui/w2ui-1.3.2.css') ?>" />
	<script src="<?=$this->basepath('public/w2ui/w2ui-1.3.2.js') ?>"></script>
	
	<link href="<?=$this->basepath('public/css/menu/master.css') ?>" rel="stylesheet">
	<link href="<?=$this->basepath('public/css/menu/bootstrap.css') ?>" rel="stylesheet">
	
	
<!-- 	<script type="text/javascript" src="/js/menuPrincipal.js"></script> -->
	
</head>
<body>

	<?php require_once 'public/menuTopo.phtml';?>

<!-- 	<div id="barraPrincipal"></div> -->
	<div id="conteudo" class="container">
<!-- 		<header> -->
<!-- 			<p>Controle dos Bichos Frenéticos</p> -->
<!-- 		</header> -->
		<?php echo $this->content; ?>
		<hr>
		<footer class="footer">
			<div class="container">
				<p>
					&copy; 2014.
					<?php echo $this->translate('Todos os direitos reservados.') ?>
				</p>
			</div>
		</footer>
	</div>
	<!-- /container -->
</body>
</html>
