
<?php require_once 'public/menuCadastro.phtml';?>

<script type="text/javascript">
<!--

//-->
$(function() {
	$('#opcaoCadastro').addClass('active');
	$('#opcaoRota').addClass('active');
	
});

</script>

<h1><?=$this->escapeHtml($this->title)?></h1>

<p>
    <a href="<?=$this->urlAdd?>"><button type="button" class="btn btn-primary">Nova Rota</button></a>
</p>

<?=$this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
<?=$this->flashMessenger()->render('error', array('alert', 'alert-danger'));?>

<?
$form = $this->formPesquisa;
$form->setAttribute('action', $this->urlPesquisa);
$form->prepare();
?>
<?=$this->form()->openTag($form)?>
<?=$this->formCollection($form)?>
<?=$this->form()->closeTag()?>


<br />
<table class="full_table_list">
<tr>
    <th>Código</th>
    <th>Nome</th>
    <th>Agencia</th>
    <th>Ação</th>
</tr>
<?=$this->partialLoop('cadastro/rota/rotas.phtml', $this->paginator)?>
</table>
 <p>
 <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination', array('route' => 'rota')); ?>
</p>

