<tr>
<td><?=str_pad($this->model->codigo,4, 0, STR_PAD_LEFT)?></td>
    <td><?=$this->escapeHtml($this->model->nome)?></td>
    <td><?=str_pad($this->model->agencia->codigo,2, 0, STR_PAD_LEFT)."-".$this->escapeHtml($this->model->agencia->nome)?></td>
    <td>
        <div align="center">
            <a href="<?=$this->placeholder('url')->edit . '/'. $this->model->id?>"><input type="submit" value="Editar"/></a>
            <a href="<?=$this->placeholder('url')->delete . '/'. $this->model->id?>"><input type="submit" value="Remover"/></a>
        </div>
    </td>
</tr>